version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-automation
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # Authentification basique
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD:-changeme123}
      
      # Configuration réseau
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      
      # Configuration générale
      - NODE_ENV=production
      - WEBHOOK_URL=${N8N_PROTOCOL:-http}://${N8N_HOST:-localhost}:5678/
      - GENERIC_TIMEZONE=Europe/Paris
      
      # Langue
      - N8N_DEFAULT_LOCALE=fr
      
      # Logs
      - N8N_LOG_LEVEL=info
      - N8N_LOG_OUTPUT=console
      
      # Sécurité
      - N8N_SECURE_COOKIE=false
      
    volumes:
      # Persistance des données
      - n8n_data:/home/node/.n8n
      
      # Workflows (optionnel - pour backup)
      - ./workflows:/home/node/.n8n/workflows
      
    networks:
      - n8n-network
    
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  n8n_data:
    driver: local

networks:
  n8n-network:
    driver: bridge
